fs:
  mountpoint: /tmp/gitlabfs/test/mnt/gitlab
  mountoptions: nodev
  forge: gitlab

gitlab:
  url: https://example.com
  token: "12345"
  pull_method: ssh
  group_ids:
    - 123
  user_ids:
    - 456
  archived_project_handling: hide
  include_current_user: true

github:
  token: "12345"
  pull_method: http
  org_names: 
    - test-org
  user_names:
    - test-user
  archived_repo_handling: hide
  include_current_user: true

gitea:
  url: https://example.com
  token: "12345"
  pull_method: http
  org_names: 
    - test-org
  user_names:
    - test-user
  archived_repo_handling: hide
  include_current_user: true

git:
  clone_location: /tmp/gitlabfs/test/cache/gitlab
  remote: origin
  on_clone: clone
  auto_pull: false
  depth: 0
  queue_size: 100
  worker_count: 1